[ApAuthService]
DefaultPwd = 'Qaz@2020'
AutoMigrate = true
Disabled = false
EID = 'c21f4f863a974fb182c9ae4cf05dc142'
InAddressField = 'IP'
InAgentField = 'User-Agent'
LimitedSlots = ''
LockAfterFails = 5
Name = 'ap'
OutAddressField = 'ip'
OutAgentField = 'agent'
PwdEncoding = 'base64'
PwdMaxLen = 8
PwdMinLen = 6
PwdNumberAndLetter = false
PwdSecret = ''
PwdSymbol = false
PwdSymbols = '{{base64:JF4mKigpPXx7fSc6IVtdXy0rfi48Pg==}}'
PwdUpperAndLowerLetter = false
SessionCreateSlot = 'createToken'
SessionRevokeSlot = 'revokeToken'
SessionService = 'session'
SessionVerifySlot = 'verifyToken'
SuperFails = 0
SuperName = 'victor'
SuperPwd = '89c766f8cf1624a178f4c8cf599d978b'